version: '3.8'

services:
    # Laravel App (PHP)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql

    # MySQL
    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mysql

volumes:
    db_data:
